# Generated by Django 4.2.7 on 2023-12-08 17:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('album', '0002_artist_album_created_at_album_updated_at_song_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Song',
        ),
    ]
